import type { Assessment } from "@/lib/carbon";

export function makeAssessment(overrides: Partial<Assessment> = {}): Assessment {
  return {
    id: "test",
    createdAt: new Date("2025-01-01").toISOString(),
    electricityKwh: 200,
    householdSize: 2,
    acHoursPerDay: 2,
    cookingFuel: "lpg_1",
    waterTier: "5to10k",
    carKm: 100,
    motorcycleKm: 0,
    busKm: 20,
    metroKm: 10,
    bicycleKm: 0,
    walkingKm: 0,
    fuelType: "petrol",
    shortFlights: 0,
    longFlights: 0,
    diet: "mixed",
    redMeatPerWeek: 2,
    whiteMeatPerWeek: 3,
    dairy: "medium",
    foodWaste: "sometimes",
    trash: "one_bin",
    recycling: "often",
    clothing: "6_15",
    electronics: "3to5y",
    reusables: "sometimes",
    improveArea: "transportation",
    willingness: "moderate",
    ...overrides,
  };
}

export const ZERO_ASSESSMENT: Assessment = makeAssessment({
  electricityKwh: 0,
  householdSize: 1,
  acHoursPerDay: 0,
  cookingFuel: "lpg_lt1",
  waterTier: "lt5k",
  carKm: 0,
  motorcycleKm: 0,
  busKm: 0,
  metroKm: 0,
  shortFlights: 0,
  longFlights: 0,
  diet: "vegan",
  redMeatPerWeek: 0,
  whiteMeatPerWeek: 0,
  dairy: "none",
  foodWaste: "rarely",
  trash: "small_bag",
  recycling: "always",
  clothing: "0_5",
  electronics: "5y",
  reusables: "always",
  improveArea: "energy",
  willingness: "small",
});

export const HIGH_EMISSION_ASSESSMENT: Assessment = makeAssessment({
  electricityKwh: 2000,
  householdSize: 1,
  acHoursPerDay: 10,
  cookingFuel: "lpg_3plus",
  waterTier: "gt20k",
  carKm: 500,
  motorcycleKm: 100,
  busKm: 0,
  metroKm: 0,
  fuelType: "diesel",
  shortFlights: 6,
  longFlights: 4,
  diet: "heavy_meat",
  redMeatPerWeek: 10,
  whiteMeatPerWeek: 7,
  dairy: "high",
  foodWaste: "always",
  trash: "more",
  recycling: "never",
  clothing: "30plus",
  electronics: "lt1y",
  reusables: "rarely",
  improveArea: "transportation",
  willingness: "major",
});
